services:
  eikona.tessa.controller.apireferencedata:
    class: Eikona\Tessa\ReferenceDataAttributeBundle\Controller\ApiController
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'

  # Decorate original
  eikona.tessa.controller.file:
    public: true
    class: Eikona\Tessa\ReferenceDataAttributeBundle\Controller\FileController
    decorates: pim_enrich.controller.file
    arguments:
      - '@.inner'
      - '@eikona.tessa.controller.media'
