eikona_tessa_media_preview:
    path: /show/{assetId}
    defaults: { _controller: eikona.tessa.controller.media:previewAction }
    methods: [GET]
eikona_tessa_media_detail:
    path: /detail/{assetId}
    defaults: { _controller: eikona.tessa.controller.media:detailAction }
    methods: [GET]
eikona_tessa_media_select:
    path: /select/{data}
    defaults: { _controller: eikona.tessa.controller.media:selectAction }
    methods: [GET]
