pim_eikona_tessa_connector:
  settings:
    base_url:
      value: ~
      scope: app
    ui_url:
      value: ~
      scope: app
    use_http_internally:
      value: false
      scope: app
    username:
      value: ~
      scope: app
    api_key:
      value: ~
      scope: app
    system_identifier:
      value: ~
      scope: app
    disable_asset_editing_in_akeneo_ui:
      value: false
      scope: app
    enable_reference_entity_tessa_main_image:
      value: false
      scope: app

