tessa_media:
    resource: 'Routing/media.yml'
    prefix: /tessa/media

internal_api:
  resource: 'Routing/internal_api.yml'
  prefix: /tessa-connector-api

eikona_tessa_connector_info:
  path: /tessa-connector/info

eikona_tessa_connector_settings:
  path: /tessa-connector/settings
